export const UPDATE_BILLING_KEY = 'UPDATE_BILLING_KEY'
export const UPDATE_SHIPPING_KEY = 'UPDATE_SHIPPING_KEY'
export const UPDATE_PAYMENT_KEY = 'UPDATE_PAYMENT_KEY'
export const SET_SHIPPING_TO_BILLING = 'SET_SHIPPING_TO_BILLING'
